package com.atos.paybatch.stubs.financialallocation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2025-11-04T17:43:55.393+02:00
 * Generated source version: 3.6.3
 *
 */
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_7", name = "FinancialAllocationWriteService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FinancialAllocationWriteService {

    /**
     * <![CDATA[<p>Write a financial allocation.</p><p>The <code>AMOUNT</code> arguments specified to transaction, document and line item levels</p><p>can be gross or net amounts depending on <code>ALLOCATION_METHOD</code> allocation method.</p><p>If optional <code>ALLOCATION_METHOD</code> is not specified <code>AMOUNT</code> is gross.</p><p>Allocation method:
     *     <ul><li>'GROSS' - gross</li><li>'NET' - net</li><li>'NETTAX' - gross</li></ul></p>]]>
     */
    @WebMethod
    @WebResult(name = "financialAllocationWriteResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_7/financialallocationwrite", partName = "financialAllocationWriteResponse")
    public FinancialAllocationWriteResponse financialAllocationWrite(

        @WebParam(partName = "financialAllocationWriteRequest", name = "financialAllocationWriteRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_7/financialallocationwrite")
        FinancialAllocationWriteRequest financialAllocationWriteRequest
    );
}
