package com.atos.paybatch.stubs.financialallocation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2025-11-02T16:00:40.894+02:00
 * Generated source version: 3.6.3
 *
 */
@WebServiceClient(name = "FinancialAllocationWriteService",
                  wsdlLocation = "file:/C:/Users/ato.amr.herek/git/OJO-PayBatchTool/src/main/resources/wsdl/ws_CIL_7_FinancialAllocationWriteService.wsdl",
                  targetNamespace = "http://ericsson.com/services/ws_CIL_7")
public class FinancialAllocationWriteService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://ericsson.com/services/ws_CIL_7", "FinancialAllocationWriteService");
    public static final QName FinancialAllocationWriteServiceSoap11 = new QName("http://ericsson.com/services/ws_CIL_7", "FinancialAllocationWriteServiceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ato.amr.herek/git/OJO-PayBatchTool/src/main/resources/wsdl/ws_CIL_7_FinancialAllocationWriteService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FinancialAllocationWriteService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ato.amr.herek/git/OJO-PayBatchTool/src/main/resources/wsdl/ws_CIL_7_FinancialAllocationWriteService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FinancialAllocationWriteService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FinancialAllocationWriteService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinancialAllocationWriteService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns FinancialAllocationWriteService
     */
    @WebEndpoint(name = "FinancialAllocationWriteServiceSoap11")
    public FinancialAllocationWriteService getFinancialAllocationWriteServiceSoap11() {
        return super.getPort(FinancialAllocationWriteServiceSoap11, FinancialAllocationWriteService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinancialAllocationWriteService
     */
    @WebEndpoint(name = "FinancialAllocationWriteServiceSoap11")
    public FinancialAllocationWriteService getFinancialAllocationWriteServiceSoap11(WebServiceFeature... features) {
        return super.getPort(FinancialAllocationWriteServiceSoap11, FinancialAllocationWriteService.class, features);
    }

}
