spring.application.name=PayBatchTool

paybatch.schedule.interval=1m

payment.input-dir=C:\\Users\\ato.amr.herek\\paybatch\\input
payment.processed-dir=C:\\Users\\ato.amr.herek\\paybatch\\processed
payment.error-dir=C:\\Users\\ato.amr.herek\\paybatch\\error
payment.duplicate-dir=C:\\Users\\ato.amr.herek\\paybatch\\duplicate

# SOAP retry configuration
financialallocation.api.max-retries=3
financialallocation.api.retry-delay-ms=2000
customersearch.api.max-retries=3
customersearch.api.retry-delay-ms=2000


# SOAP credentials & end points
soap.username=TestMunther
soap.password=cV1#nX6r!8JkP3y&
bscs.webservices.endpoint=http://hsm-billing-soi-1-e:9052/wsi/services/


#SOAP logging control
soap.logging.enabled=false
soap.logging.limit=0


# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hsm-bscs-db-1-e.jt.jtgroup)(PORT=1541))(CONNECT_DATA=(SERVICE_NAME=OJPPBSC)))
spring.datasource.username=SYSADM
spring.datasource.password=EBADM#123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


