package com.atos.paybatch.stubs.customerread;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2026-04-03T00:16:15.897+03:00
 * Generated source version: 3.6.3
 *
 */
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_7", name = "CustomerReadService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerReadService {

    /**
     * <![CDATA[<p>Read a particular customer/dealer through a given internal BSCS customer ID.</p><p>Not all output parameter are returned for the dealer.</p>]]>
     */
    @WebMethod
    @WebResult(name = "customerReadResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_7/customerread", partName = "customerReadResponse")
    public CustomerReadResponse customerRead(

        @WebParam(partName = "customerReadRequest", name = "customerReadRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_7/customerread")
        CustomerReadRequest customerReadRequest
    );
}
