package com.atos.paybatch.stubs.customersearch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2026-04-02T14:07:16.151+02:00
 * Generated source version: 3.6.3
 *
 */
@WebService(targetNamespace = "http://ericsson.com/services/ws_CIL_7", name = "CustomersSearchService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomersSearchService {

    /**
     * <![CDATA[<p>Search customers through a number of criteria from customer and contract data.</p>]]>
     */
    @WebMethod
    @WebResult(name = "customersSearchResponse", targetNamespace = "http://ericsson.com/services/ws_CIL_7/customerssearch", partName = "customersSearchResponse")
    public CustomersSearchResponse customersSearch(

        @WebParam(partName = "customersSearchRequest", name = "customersSearchRequest", targetNamespace = "http://ericsson.com/services/ws_CIL_7/customerssearch")
        CustomersSearchRequest customersSearchRequest
    );
}
