package com.atos.paybatch.stubs.customersearch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.3
 * 2026-04-02T14:07:16.185+02:00
 * Generated source version: 3.6.3
 *
 */
@WebServiceClient(name = "CustomersSearchService",
                  wsdlLocation = "file:/C:/ATOS/18-OJO/00-Delivery/BSCS%20Upgrade/02.%20Delivery%20Phase/PIH/01.workspace/PayBatchTool/src/main/resources/wsdl/ws_CIL_7_CustomersSearchService.wsdl",
                  targetNamespace = "http://ericsson.com/services/ws_CIL_7")
public class CustomersSearchService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://ericsson.com/services/ws_CIL_7", "CustomersSearchService");
    public static final QName CustomersSearchServiceSoap11 = new QName("http://ericsson.com/services/ws_CIL_7", "CustomersSearchServiceSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/ATOS/18-OJO/00-Delivery/BSCS%20Upgrade/02.%20Delivery%20Phase/PIH/01.workspace/PayBatchTool/src/main/resources/wsdl/ws_CIL_7_CustomersSearchService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomersSearchService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/ATOS/18-OJO/00-Delivery/BSCS%20Upgrade/02.%20Delivery%20Phase/PIH/01.workspace/PayBatchTool/src/main/resources/wsdl/ws_CIL_7_CustomersSearchService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomersSearchService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomersSearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersSearchService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns CustomersSearchService
     */
    @WebEndpoint(name = "CustomersSearchServiceSoap11")
    public CustomersSearchService getCustomersSearchServiceSoap11() {
        return super.getPort(CustomersSearchServiceSoap11, CustomersSearchService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersSearchService
     */
    @WebEndpoint(name = "CustomersSearchServiceSoap11")
    public CustomersSearchService getCustomersSearchServiceSoap11(WebServiceFeature... features) {
        return super.getPort(CustomersSearchServiceSoap11, CustomersSearchService.class, features);
    }

}
